notifications:
  email: false

language: python

matrix:
    include:
        - os: linux
          python: 3.7
          dist: xenial
          sudo: true

install:
  - wget https://github.com/andre-martins/AD3/archive/2.2.1.tar.gz
  - tar zxvf 2.2.1.tar.gz
  - pip install pytest numpy ad3
  - pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl
  - AD3_DIR=ad3/ python setup.py bdist_wheel
  - pip install --pre --no-index --find-links dist/ sparsemap

script:
  - echo "Running tests"
  - mkdir empty_folder; cd empty_folder; pytest -vs --pyargs sparsemap; cd ..
